pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Lucifer29082002/CI-CD-RANSOMWARE-SIMULATION.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ransomware-sim .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d --rm --name ransomware-test ransomware-sim'
            }
        }

        stage('Verify Encryption') {
            steps {
                sh 'docker exec -it ransomware-test bash -c "cat target_files/sample1.txt || true"'
            }
        }

        stage('Clean Up') {
            steps {
                sh 'docker stop ransomware-test || true'
                sh 'docker system prune -f'
            }
        }
    }

    post {
        always {
            echo 'CI/CD pipeline completed.'
        }
    }
}
