name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and test Docker image
      run: |
        docker build -t ransomware-web-sim .
        docker run -d --name test-container -p 5000:5000 ransomware-web-sim
        sleep 5
        docker ps
        curl http://localhost:5000
        docker stop test-container
      
    - name: Deploy to Render
      # Trigger Render deploy hook - you'll need to create this in Render dashboard
      # This is a webhook URL that Render provides to trigger deployments
      run: |
        curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK_URL }}